### ISSUE TITLE
Create script for video presentation

### ISSUE THREAD

**Issue by RogerHuauya** [CS1103/MNISTplusplus#10]
The script will outline the content, dialogue, and visual elements that will be included in the video. It will serve as a blueprint for the video presentation, providing guidance on what will be said, shown, and how the overall story or message will be conveyed.

In this task, the focus will be on crafting a clear and engaging narrative that effectively communicates the key points or information intended for the video presentation. The script should include a well-structured flow of ideas, engaging dialogue, and specific directions for visuals, such as graphics, animations, or footage.

**Comment by gabrielromerod** [comment]
Guión video:

https://docs.google.com/document/d/1SJ0ILXnBG_nzHG--9ZrLC5k362E2SQuEKfg1XTOVgfc/edit?usp=sharing
